package com.ow.tracer.${data.packageName}.${data.functionName}.service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.ow.tracer.${data.packageName}.${data.functionName}.dto.${data.className};
import com.ow.tracer.common.base.BaseService;

/**
 * 类描述:     [${data.describe}业务接口]
 * 创建人:     [${data.author}]
 * 创建时间:   [${date(),"yyyy-MM-dd HH:mm:ss"}]
 * 版本:       [v1.0]
 */
public interface I${data.className}Service extends BaseService<${data.className}> {



}
