package com.ow.tracer.${data.packageName}.${data.functionName}.mapper;

import com.ow.tracer.common.base.Mapper;
import com.ow.tracer.${data.packageName}.${data.functionName}.dto.${data.className};


/**
 * 类描述:     [${data.describe}数据处理接口]
 * 创建人:     [${data.author}]
 * 创建时间:   [${date(),"yyyy-MM-dd HH:mm:ss"}]
 * 版本:       [v1.0]
 */
public interface ${data.className}Mapper extends Mapper<${data.className}> {



}
